name: Package Lock Test ( Legacy )
on:
  push:
    branches:
      -  main
    paths:
      - .github/workflows/pkg-lock-test.yml
      - flake.nix
      - lib/**
      - pkgs/**
      - test/pkg-lock/**
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - .github/workflows/pkg-lock-test.yml
      - flake.nix
      - lib/**
      - pkgs/**
      - test/pkg-lock/**
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pkg-lock-tests:
    runs-on: ubuntu-latest
    env:
      SYSTEM: x86_64-linux
    steps:
      - uses: cachix/install-nix-action@d64e0553100205688c0fb2fa16edb0fc8663c590
        with:
          nix_path: nixpkgs=channel:nixpkgs-22.05
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://cache.nixos.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            max-jobs = auto
            cores = 0
            substitute = true
            builders-use-substitutes = true
            fallback = true
            connect-timeout = 5
            stalled-download-timeout = 90
            timeout = 0
      - name: Setup
        run: |
          echo "# ============================================================================ #" >&2;
          { printf '    bash   version: '; bash   --version|head -n1; } >&2;
          { printf '    nix    version: '; nix    --version; } >&2;
          echo "# ---------------------------------------------------------------------------- #" >&2;
          # Register aliases to avoid the long ref
          nix registry add head-root "github:aameen-tulip/at-node-nix/$GITHUB_REF";
          nix registry add head      "github:aameen-tulip/at-node-nix/$GITHUB_REF?dir=test/pkg-lock";
          nix registry add nixpkgs   "github:NixOS/nixpkgs/29769d2a1390d294469bcc6518f17931953545e1";

      - name: Ideal Tree PlockV2 ( Build )
        run: nix build head
      - name: Ideal Tree PlockV2 ( Build with Root Inputs )
        run: nix build head --inputs-from head-root
      - name: Ideal Tree PlockV2 ( Check with Root Inputs )
        run: nix flake check head --inputs-from head-root
